### ISSUE TITLE
fetchResults has no change on useQuery

### ISSUE THREAD

**Issue by brunomperes** [vuejs/apollo#1060]
**Describe the bug**
On `v4`, passing the option `fetchResults: false` to `useQuery` has no effect (and if it had any I'm not clear how it is different from `enabled: false`)

**To Reproduce**
1. Add `fetchResults: false` option to a component with composition API
2. Render the page
3. See component still fetching results on the server and on the client

**Expected behavior**
From what I see this option only exists in the v4 branch [in a doc page](https://github.com/vuejs/vue-apollo/blob/v4/packages/docs/src/api/use-query.md#L31) and [in a test](https://github.com/vuejs/vue-apollo/blob/v4/packages/vue-apollo-composable/tests/types/useQuery-types.test.ts#L134).

So perhaps it's a leftover from v3 and it's just a matter of removing it.

If it is to be implemented though, ideally would be clear what is the difference between `fetchResults` and `enabled`

**Versions**
vue: 2.6.12
vue-apollo: v4.0.0-alpha.10
apollo-client: 3.1.2

**Additional context**
Link to docs page: https://v4.apollo.vuejs.org/api/use-query.html#parameters

**Comment by karladler** [comment]
This seems to be still an issue or it requires some documentation.

**Comment by karladler** [comment]
any update here?
