### ISSUE TITLE
The jsFiddle in the docs for the demo is broken

### ISSUE THREAD

**Issue by cosimochellini** [vuejs/apollo#634]
the link for the demo https://jsfiddle.net/Akryum/oyejk2qL/ in the home (https://vue-apollo.netlify.com/guide/#links) don't work

**Comment by flygare** [comment]
Seems like the certificate for the graphql endpoint has expired

**Comment by Akryum** [comment]
Apollo Launchpad has been shutdown, I need to do a replacement (for example, using Codesandbox).
